version: '3.7'

services:
  app1-api:
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./api:/go/src/app1/api
    environment:
      - SCOPE=local
    ports:
      - "8080:8080"

